# This is a basic workflow to help you get started with Actions

name: buildrelease

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches:
#      - $default-branch
      - rolinge/gitactions
    # Publish `v1.2.3` tags as releases.
#    tags:
#      - P/*

#  pull_request:
#    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: "Echo variables"
        run: |
          echo "REF:  $GITHUB_REF , SHA: $GITHUB_SHA , ACTION:  $GITHUB_ACTION "

      - name: "Overwrite Symlinks"
        run: rm -fr barista-scan/src/{models,services,shared} && cp -r barista-api/src/{models,services,shared} barista-scan/src;

      - name: "Build with compose"
        run:  cp -f docker-compose/docker-compose-build.yaml ./docker-compose.yaml &&  docker-compose build

  login:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: "Log into Registry"
        run:  echo "${{ secrets.DOCKERIO_TOKEN}}" | docker login -u ospo4optum --password-stdin

  publishtest:
    needs: login
    runs-on: ubuntu-latest
    if:
    steps:
      - name: "Tag and push images"
        run: |
          for i in api web scan base scanbase
            do
              docker tag barista-${i}:compose optumopensource/barista-${i}:testcompose
              docker push optumopensource/barista-${i}:testcompose
            done
